---
- name: Update and upgrade apt packages
  apt:
    update_cache: yes
    upgrade: yes
  become: yes
  tags:
    - update_upgrade

- name: Install essential packages
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - git
    - curl
    - wget
    - tmux
    - expect
  become: yes
  tags:
    - essentials

- name: Install zsh
  apt:
    name: zsh
    state: present
  become: yes
  tags:
    - zsh

- name: Get the current shell for the user
  command: echo $SHELL
  register: current_shell
  changed_when: false
  tags:
    - zsh

- name: Get the path of zsh
  shell: which zsh
  register: zsh_path
  become: no
  tags:
    - debug

- name: Switch to zsh using expect
  expect:
    command: "chsh -s {{ zsh_path.stdout }}"
    responses:
      (?i)password: "{{ my_password }}"
  when: current_shell.stdout != zsh_path.stdout
  become: no
  tags:
    - zsh

- name: Source .zshrc to apply changes
  shell: source {{ ansible_user_dir }}/.zshrc
  args:
    executable: /bin/zsh
  when: current_shell.stdout != zsh_path.stdout
  become: no
  tags:
    - zsh

- name: Add VSCode repository and install
  block:
    - name: Import Microsoft GPG key
      apt_key:
        url: https://packages.microsoft.com/keys/microsoft.asc
        state: present
    - name: Add VSCode repository
      apt_repository:
        repo: deb [arch=amd64,arm64,armhf] https://packages.microsoft.com/repos/code stable main
        state: present
    - name: Install VSCode
      apt:
        name: code
        state: present
        update_cache: yes
  become: yes
  tags:
    - vscode
